# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_cosmos_tx_parsing.ipynb.

# %% ../nbs/00_cosmos_tx_parsing.ipynb #b3a8da2b
from __future__ import annotations

import logging
import re
from decimal import Decimal
from typing import Any, Dict, List, Optional, Tuple

from .common import MICRO, NYM_DENOM, to_int

# %% auto #0
__all__ = ['COIN_RE', 'attr_map', 'extract_events', 'node_id_from_attrs', 'parse_coins', 'events_by_msg_index',
           'sum_incoming_unym_from_events', 'sum_incoming_nym_from_events']

# %% ../nbs/00_cosmos_tx_parsing.ipynb #40c234a1
def attr_map(attrs: Any) -> Dict[str, str]:
    out: Dict[str, str] = {}
    if not isinstance(attrs, list):
        return out
    for a in attrs:
        if not isinstance(a, dict):
            continue
        k = str(a.get("key") or "")
        if not k:
            continue
        out[k] = str(a.get("value") or "")
    return out


def extract_events(tx_response_or_like: Dict[str, Any]) -> List[Dict[str, Any]]:
    rows: List[Dict[str, Any]] = []
    for ev in (tx_response_or_like.get("events") or []):
        if not isinstance(ev, dict):
            continue
        rows.append({"type": str(ev.get("type") or ""), "attributes": attr_map(ev.get("attributes"))})
    return rows

# %% ../nbs/00_cosmos_tx_parsing.ipynb #6064c904
def node_id_from_attrs(attrs: Dict[str, str]) -> Optional[int]:
    for key in ("node_id", "delegation_target", "mix_id"):
        v = to_int(attrs.get(key))
        if v is not None:
            return v
    return None

# %% ../nbs/00_cosmos_tx_parsing.ipynb #f26f2c05
COIN_RE = re.compile(r"^(\d+)([a-zA-Z][a-zA-Z0-9/]*)$")


def parse_coins(amount_str: str) -> List[Tuple[int, str]]:
    out: List[Tuple[int, str]] = []
    for part in (amount_str or "").split(","):
        part = part.strip()
        if not part:
            continue
        m = COIN_RE.match(part)
        if not m:
            continue
        out.append((int(m.group(1)), m.group(2)))
    return out

# %% ../nbs/00_cosmos_tx_parsing.ipynb #b277b11b
def events_by_msg_index(
    tx_resp: Dict[str, Any],
    *,
    prefer_logs: bool = True,
    logger: Optional[logging.Logger] = None,
    txhash: str = "",
) -> Dict[int, List[Dict[str, Any]]]:
    out: Dict[int, List[Dict[str, Any]]] = {}

    if prefer_logs:
        for lg in (tx_resp.get("logs") or []):
            mi = to_int((lg or {}).get("msg_index"))
            if mi is None:
                continue
            evs = (lg or {}).get("events") or []
            if isinstance(evs, list):
                out[int(mi)] = [e for e in evs if isinstance(e, dict)]

    if out:
        return out

    raw_events = [e for e in (tx_resp.get("events") or []) if isinstance(e, dict)]
    normalized = extract_events({"events": raw_events})
    for raw_ev, norm_ev in zip(raw_events, normalized):
        mi = to_int((norm_ev.get("attributes") or {}).get("msg_index"))
        if mi is None:
            continue
        out.setdefault(int(mi), []).append(raw_ev)

    if out and logger:
        logger.debug("Reconstructed events by msg_index tx=%s indexes=%s", txhash, sorted(out.keys()))

    return out

# %% ../nbs/00_cosmos_tx_parsing.ipynb #b181e519
def sum_incoming_unym_from_events(events: List[Dict[str, Any]], recipient: str) -> int:
    transfer_unym = 0
    coin_received_unym = 0

    for ev in events:
        ev_type = str(ev.get("type") or ev.get("kind") or "")
        if ev_type not in ("transfer", "coin_received"):
            continue

        recv_key = "recipient" if ev_type == "transfer" else "receiver"
        attrs = ev.get("attributes") or []
        if not isinstance(attrs, list):
            continue

        receivers = {
            str((a.get("value") or "")).strip()
            for a in attrs
            if (a.get("key") or a.get("name") or "") == recv_key
        }
        if recipient not in receivers:
            continue

        for a in attrs:
            if (a.get("key") or a.get("name") or "") != "amount":
                continue
            for amt, denom in parse_coins(str(a.get("value") or "")):
                if denom != NYM_DENOM:
                    continue
                if ev_type == "transfer":
                    transfer_unym += int(amt)
                else:
                    coin_received_unym += int(amt)

    return transfer_unym if transfer_unym > 0 else coin_received_unym


def sum_incoming_nym_from_events(events: List[Dict[str, Any]], recipient: str) -> Decimal:
    return Decimal(sum_incoming_unym_from_events(events, recipient)) / MICRO
