# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_reward_transactions.ipynb.

# %% ../nbs/03_reward_transactions.ipynb #4afdb0cc-43f5-480a-8c60-a0deb7e2cf29
from __future__ import annotations

import base64
import bisect
import csv
import datetime as dt
import json
import logging
from decimal import Decimal
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

from pydantic import BaseModel, ConfigDict
from tabulate import tabulate
from tqdm import tqdm

from nym_node_reward_tracker.cosmos_tx_parsing import (
    attr_map,
    events_by_msg_index,
    extract_events,
    node_id_from_attrs,
    parse_coins,
    sum_incoming_nym_from_events,
)
from nym_node_reward_tracker.common import (
    DEFAULT_TIMEOUT_S,
    MICRO,
    NYM_DENOM,
    build_session,
    build_tx_query,
    iter_txs_by_query,
    parse_date_filters,
    parse_rfc3339_to_utc,
    read_wallets_csv,
    request_json,
    setup_logging,
    to_decimal,
    to_int,
)

DEFAULT_NYX_API_BASE = "https://api.nymtech.net"
DEFAULT_NYX_TX_REST = f"{DEFAULT_NYX_API_BASE}/cosmos/tx/v1beta1/txs"

DEFAULT_COINGECKO_BASE = "https://api.coingecko.com/api/v3"
DEFAULT_TX_API_BASE = DEFAULT_NYX_TX_REST
DEFAULT_TX_RPC_BASE = "https://rpc.nymtech.net"

# Keep this overrideable via CLI arg --mixnet-contract.
DEFAULT_MIXNET_CONTRACT = "n17srjznxl9dvzdkpwpw24gg668wc73val88a6m5ajg6ankwvz9wtst0cznr"

REWARD_ACTION_KEYS = {
    "withdraw_operator_reward",
    "withdraw_delegator_reward",
    "withdraw_operator_reward_on_behalf",
    "withdraw_delegator_reward_on_behalf",
    "compound_operator_reward",
    "compound_delegator_reward",
    "claim_operator_reward",
    "claim_delegator_reward",
}


# %% auto #0
__all__ = ['DEFAULT_NYX_API_BASE', 'DEFAULT_NYX_TX_REST', 'DEFAULT_COINGECKO_BASE', 'DEFAULT_TX_API_BASE', 'DEFAULT_TX_RPC_BASE',
           'DEFAULT_MIXNET_CONTRACT', 'REWARD_ACTION_KEYS', 'WITHDRAW_WASM_EVENT_TO_ACTION', 'WalletRow',
           'RewardMessage', 'RewardTxRow', 'load_wallets', 'decode_execute_msg', 'extract_action',
           'node_id_from_wasm_events', 'node_id_from_tx_response_events', 'sum_fee_nym', 'resolve_tx_url',
           'build_reward_rows_for_tx', 'fetch_coingecko_prices_range', 'nearest_price', 'enrich_rows_with_prices',
           'log_rows_table', 'write_rows', 'run_reward_transactions']

# %% ../nbs/03_reward_transactions.ipynb #470c0a38-e74f-4baf-973c-39d0c68fdff1
class WalletRow(BaseModel):
    """Wallet input row from CSV (`address`, optional `tag`)."""
    model_config = ConfigDict(frozen=True)

    address: str
    tag: str = ""

class RewardMessage(BaseModel):
    """Parsed reward withdrawal message with resolved `node_id` and action kind."""
    msg_index: int
    action: str
    node_id: int | None = None


class RewardTxRow(BaseModel):
    """Normalized reward-withdrawal transaction row before fiat enrichment/export."""
    timestamp_utc: str
    wallet: str
    tag: str = ""
    txhash: str
    tx_url: str
    height: str = ""
    msg_index: int
    action: str
    node_id: int | None = None
    amount_nym: str
    tx_fee_nym: str
    fee_alloc_nym: str
    net_nym: str
    price_timestamp_utc: str = ""
    price_time_diff_seconds: str = ""


def load_wallets(wallets_csv: str | Path) -> List[WalletRow]:
    rows = read_wallets_csv(wallets_csv)
    return [WalletRow(address=a, tag=t) for a, t in rows]


# %% ../nbs/03_reward_transactions.ipynb #d7e8f6b4-fcd8-4af8-b9d4-91c102bf4c20
def decode_execute_msg(msg_field: Any) -> Optional[Dict[str, Any]]:
    if isinstance(msg_field, dict):
        return msg_field
    if isinstance(msg_field, str):
        s = msg_field.strip()
        if not s:
            return None
        try:
            raw = base64.b64decode(s)
            return json.loads(raw.decode("utf-8"))
        except Exception:
            try:
                return json.loads(s)
            except Exception:
                return None
    return None


def extract_action(exec_msg: Dict[str, Any]) -> str:
    return next(iter(exec_msg.keys()), "") if isinstance(exec_msg, dict) else ""


# %% ../nbs/03_reward_transactions.ipynb #46f7a42d-2644-4867-8b3b-f838be714ca2
WITHDRAW_WASM_EVENT_TO_ACTION = {
    "wasm-v2_withdraw_operator_reward": "withdraw_operator_reward",
    "wasm-v2_withdraw_delegator_reward": "withdraw_delegator_reward",
}


def _reward_withdrawals_from_events_by_index(
    ev_by_idx: Dict[int, List[Dict[str, Any]]],
    *,
    mixnet_contract: str,
) -> List[Dict[str, Any]]:
    out: List[Dict[str, Any]] = []
    for msg_index, evs in sorted(ev_by_idx.items()):
        base_action: Optional[str] = None
        node_id: Optional[int] = None
        for ev in evs:
            et = str(ev.get("type") or "")
            if et not in WITHDRAW_WASM_EVENT_TO_ACTION:
                continue
            attrs = attr_map(ev.get("attributes"))
            contract = attrs.get("_contract_address") or ""
            if contract and mixnet_contract and contract != mixnet_contract:
                continue
            base_action = WITHDRAW_WASM_EVENT_TO_ACTION[et]
            node_id = node_id_from_attrs(attrs)
            break
        if base_action:
            out.append({"msg_index": int(msg_index), "action": base_action, "node_id": node_id})
    return out


def _enrich_action_from_message(
    messages: List[Dict[str, Any]],
    *,
    msg_index: int,
    mixnet_contract: str,
) -> Optional[str]:
    if msg_index < 0 or msg_index >= len(messages):
        return None
    msg = messages[msg_index]
    if str(msg.get("@type") or "").endswith("MsgExecuteContract") is False:
        return None
    if mixnet_contract and str(msg.get("contract") or "").strip() != mixnet_contract:
        return None
    exec_msg = decode_execute_msg(msg.get("msg"))
    if not exec_msg:
        return None
    action = extract_action(exec_msg)
    return action if action in REWARD_ACTION_KEYS else None


# %% ../nbs/03_reward_transactions.ipynb #7615b457-4e80-46a1-929a-863dcf897903
def node_id_from_wasm_events(events: List[Dict[str, Any]]) -> Optional[int]:
    for ev in events:
        et = str(ev.get("type") or "")
        if not et.startswith("wasm"):
            continue
        nid = node_id_from_attrs(attr_map(ev.get("attributes")))
        if nid is not None:
            return nid
    return None


def node_id_from_tx_response_events(tx_resp: Dict[str, Any]) -> Optional[int]:
    for ev in extract_events(tx_resp):
        et = str(ev.get("type") or "")
        if not et.startswith("wasm"):
            continue
        nid = node_id_from_attrs(ev.get("attributes") or {})
        if nid is not None:
            return nid
    return None


# %% ../nbs/03_reward_transactions.ipynb #839b0473-8753-487f-8a8b-d005aa00c03d
def sum_fee_nym(tx: Dict[str, Any]) -> Decimal:
    fee = (((tx or {}).get("auth_info") or {}).get("fee") or {})
    total_unym = 0
    for c in (fee.get("amount") or []):
        if not isinstance(c, dict):
            continue
        if c.get("denom") == NYM_DENOM:
            total_unym += int(to_int(c.get("amount"), 0) or 0)
    return Decimal(total_unym) / MICRO


# %% ../nbs/03_reward_transactions.ipynb #f15ed915
def _tx_url_candidates(
    txhash: str,
    *,
    explorer_base: str,
    tx_api_base: str,
    tx_rpc_base: str,
) -> List[Tuple[str, str]]:
    h = txhash.strip()
    raw = [
        ("explorer", f"{explorer_base.rstrip('/')}/{h}"),
        ("tx_api", f"{tx_api_base.rstrip('/')}/{h}"),
        ("tx_rpc", f"{tx_rpc_base.rstrip('/')}/tx?hash=0x{h}&prove=false"),
    ]
    out: List[Tuple[str, str]] = []
    seen: set[str] = set()
    for kind, url in raw:
        if url in seen:
            continue
        seen.add(url)
        out.append((kind, url))
    return out


def _tx_url_is_reachable(
    session: Any,
    *,
    kind: str,
    url: str,
    timeout: int,
    logger: logging.Logger,
) -> bool:
    try:
        if kind in ("tx_api", "tx_rpc"):
            js = request_json(session, url, timeout=timeout, retries=2, logger=logger)
            if not isinstance(js, dict):
                return False
            if kind == "tx_api":
                return isinstance(js.get("tx_response"), dict)
            return isinstance(js.get("result"), dict)

        resp = session.get(url, timeout=timeout)
        return int(getattr(resp, "status_code", 0) or 0) < 400
    except Exception as exc:
        logger.debug("tx_url check failed kind=%s url=%s err=%s", kind, url, exc)
        return False


def resolve_tx_url(
    txhash: str,
    *,
    session: Any | None,
    explorer_base: str,
    tx_api_base: str,
    tx_rpc_base: str,
    timeout: int,
    logger: logging.Logger,
) -> str:
    candidates = _tx_url_candidates(
        txhash,
        explorer_base=explorer_base,
        tx_api_base=tx_api_base,
        tx_rpc_base=tx_rpc_base,
    )
    if session is None:
        return candidates[0][1]

    for kind, url in candidates:
        if _tx_url_is_reachable(session, kind=kind, url=url, timeout=timeout, logger=logger):
            return url

    return candidates[0][1]


# %% ../nbs/03_reward_transactions.ipynb #e17761a0-285d-4c26-80c2-0c2ea90d9c6a
def build_reward_rows_for_tx(
    *,
    wallet: WalletRow,
    tx: Dict[str, Any],
    tx_resp: Dict[str, Any],
    mixnet_contract: str,
    explorer_base: str,
    tx_api_base: str,
    tx_rpc_base: str,
    logger: logging.Logger,
    session: Any | None = None,
) -> List[Dict[str, Any]]:
    txhash = str(tx_resp.get("txhash") or tx_resp.get("hash") or "")
    if not txhash:
        return []

    timestamp = str(tx_resp.get("timestamp") or "")
    if not timestamp:
        return []
    ts_dt = parse_rfc3339_to_utc(timestamp)

    messages = (((tx or {}).get("body") or {}).get("messages") or [])
    if not isinstance(messages, list):
        messages = []
    messages = [m for m in messages if isinstance(m, dict)]

    ev_by_idx = events_by_msg_index(tx_resp, logger=logger, txhash=txhash)
    reward_msgs = _reward_withdrawals_from_events_by_index(ev_by_idx, mixnet_contract=mixnet_contract)
    if not reward_msgs:
        return []

    tx_url = resolve_tx_url(
        txhash,
        session=session,
        explorer_base=explorer_base,
        tx_api_base=tx_api_base,
        tx_rpc_base=tx_rpc_base,
        timeout=DEFAULT_TIMEOUT_S,
        logger=logger,
    )
    tx_fee_nym = sum_fee_nym(tx)
    fee_alloc = tx_fee_nym / Decimal(max(len(reward_msgs), 1))

    rows: List[Dict[str, Any]] = []
    for rm in reward_msgs:
        i = int(rm["msg_index"])
        evs = ev_by_idx.get(i, [])

        action = str(rm["action"])
        enriched = _enrich_action_from_message(messages, msg_index=i, mixnet_contract=mixnet_contract)
        if enriched:
            action = enriched

        amount_nym = sum_incoming_nym_from_events(evs, wallet.address)
        node_id = rm.get("node_id") or node_id_from_wasm_events(evs) or node_id_from_tx_response_events(tx_resp)
        net_nym = amount_nym - fee_alloc

        row = RewardTxRow(
            timestamp_utc=ts_dt.isoformat(),
            wallet=wallet.address,
            tag=wallet.tag,
            txhash=txhash,
            tx_url=tx_url,
            height=str(tx_resp.get("height") or ""),
            msg_index=i,
            action=action,
            node_id=node_id,
            amount_nym=f"{amount_nym:.6f}",
            tx_fee_nym=f"{tx_fee_nym:.6f}",
            fee_alloc_nym=f"{fee_alloc:.6f}",
            net_nym=f"{net_nym:.6f}",
        ).model_dump()
        if row.get("node_id") is None:
            row["node_id"] = ""
        rows.append(row)

    return rows


# %% ../nbs/03_reward_transactions.ipynb #470e618b-c9ff-480e-81c5-c067ed011ab9
def fetch_coingecko_prices_range(
    session: Any,
    *,
    coingecko_base: str,
    coin_id: str,
    vs_currency: str,
    from_ts: int,
    to_ts: int,
    api_key: Optional[str],
    timeout: int = DEFAULT_TIMEOUT_S,
    retries: int = 6,
    logger: Optional[logging.Logger] = None,
) -> List[Tuple[int, Decimal]]:
    url = f"{coingecko_base.rstrip('/')}/coins/{coin_id}/market_chart/range"
    params = {"vs_currency": vs_currency, "from": str(from_ts), "to": str(to_ts)}

    headers: Dict[str, str] = {}
    if api_key:
        headers["x-cg-demo-api-key"] = api_key

    js = request_json(
        session,
        url,
        params=params,
        headers=headers or None,
        timeout=timeout,
        retries=retries,
        logger=logger,
    )
    if not isinstance(js, dict):
        return []

    points: List[Tuple[int, Decimal]] = []
    for item in (js.get("prices") or []):
        if not isinstance(item, (list, tuple)) or len(item) < 2:
            continue
        t_ms, px = item[0], item[1]
        dec_px = to_decimal(px)
        if dec_px is None:
            continue
        points.append((int(int(t_ms) / 1000), dec_px))

    points.sort(key=lambda x: x[0])
    dedup: Dict[int, Decimal] = {}
    for t, px in points:
        dedup[t] = px
    return sorted(dedup.items(), key=lambda x: x[0])


def nearest_price(points: List[Tuple[int, Decimal]], ts: int) -> Tuple[Optional[int], Optional[Decimal], Optional[int]]:
    if not points:
        return (None, None, None)
    times = [p[0] for p in points]
    i = bisect.bisect_left(times, ts)

    candidates: List[Tuple[int, Decimal]] = []
    if i > 0:
        candidates.append(points[i - 1])
    if i < len(points):
        candidates.append(points[i])

    best = min(candidates, key=lambda p: abs(ts - p[0]))
    return (best[0], best[1], abs(ts - best[0]))

# %% ../nbs/03_reward_transactions.ipynb #0cfde673-2339-4ed3-b5fe-cf2be3ec071c
def enrich_rows_with_prices(
    rows: List[Dict[str, Any]],
    *,
    session: Any,
    currency: str,
    coingecko_base: str,
    coin_id: str,
    api_key: Optional[str],
    logger: logging.Logger,
) -> None:
    if not rows:
        return

    stamps = [int(parse_rfc3339_to_utc(r["timestamp_utc"]).timestamp()) for r in rows]
    from_ts = int(min(stamps)) - 3600
    to_ts = int(max(stamps)) + 3600

    logger.info("CoinGecko price window unix=%s..%s (%s)", from_ts, to_ts, currency)

    points = fetch_coingecko_prices_range(
        session,
        coingecko_base=coingecko_base,
        coin_id=coin_id,
        vs_currency=currency,
        from_ts=from_ts,
        to_ts=to_ts,
        api_key=api_key,
        logger=logger,
    )
    logger.info("Loaded %d price points", len(points))

    for r in rows:
        ts = int(parse_rfc3339_to_utc(r["timestamp_utc"]).timestamp())
        p_ts, px, diff = nearest_price(points, ts)

        amt = Decimal(str(r.get("amount_nym") or "0"))
        if px is None:
            r[f"price_{currency}_per_nym"] = ""
            r[f"value_{currency}"] = ""
            r["price_timestamp_utc"] = ""
            r["price_time_diff_seconds"] = ""
            continue

        value = amt * px
        r[f"price_{currency}_per_nym"] = f"{px:.8f}"
        r[f"value_{currency}"] = f"{value:.2f}"
        r["price_timestamp_utc"] = dt.datetime.fromtimestamp(int(p_ts), tz=dt.timezone.utc).isoformat() if p_ts else ""
        r["price_time_diff_seconds"] = str(diff if diff is not None else "")

# %% ../nbs/03_reward_transactions.ipynb #b8b01e4c-f4e9-4503-a53f-d03d63e8c4fa
def log_rows_table(rows: List[Dict[str, Any]], *, currency: str, logger: logging.Logger) -> None:
    headers = [
        "timestamp_utc",
        "wallet",
        "action",
        "node_id",
        "amount_nym",
        "net_nym",
        f"price_{currency}_per_nym",
        f"value_{currency}",
    ]
    view = [
        [
            r.get("timestamp_utc", ""),
            r.get("wallet", ""),
            r.get("action", ""),
            r.get("node_id", ""),
            r.get("amount_nym", ""),
            r.get("net_nym", ""),
            r.get(f"price_{currency}_per_nym", ""),
            r.get(f"value_{currency}", ""),
        ]
        for r in rows
    ]
    logger.info("")
    logger.info("Reward transactions (table)")
    logger.info("\n%s", tabulate(view, headers=headers, tablefmt="github", stralign="right", disable_numparse=True))


def write_rows(rows: List[Dict[str, Any]], *, currency: str, out_path: str | Path) -> None:
    p = Path(out_path)
    p.parent.mkdir(parents=True, exist_ok=True)

    fieldnames = [
        "timestamp_utc",
        "wallet",
        "tag",
        "txhash",
        "tx_url",
        "height",
        "msg_index",
        "action",
        "node_id",
        "amount_nym",
        "tx_fee_nym",
        "fee_alloc_nym",
        "net_nym",
        f"price_{currency}_per_nym",
        f"value_{currency}",
        "price_timestamp_utc",
        "price_time_diff_seconds",
    ]

    suffix = p.suffix.lower()
    if suffix == ".xlsx":
        try:
            from openpyxl import Workbook
        except ImportError as exc:
            raise RuntimeError("openpyxl is required for .xlsx output") from exc

        wb = Workbook()
        ws = wb.active
        ws.title = "reward_transactions"
        ws.append(fieldnames)
        for r in rows:
            ws.append([r.get(k, "") for k in fieldnames])
        wb.save(p)
        return

    if suffix not in ("", ".csv"):
        raise ValueError(f"Unsupported output extension '{suffix}' for {p}. Use .csv or .xlsx")

    with p.open("w", newline="", encoding="utf-8") as f:
        wtr = csv.DictWriter(f, fieldnames=fieldnames)
        wtr.writeheader()
        for r in rows:
            wtr.writerow(r)

# %% ../nbs/03_reward_transactions.ipynb #ef7c78e5-d8d7-487d-a339-99b674db07d0
def run_reward_transactions(
    *,
    wallets_csv: str = "wallet-addresses.csv",
    out_csv: str = "nym_rewards_tax_export.csv",
    currency: str = "eur",
    start: Optional[str] = None,
    end: Optional[str] = None,
    nyx_api_base: Optional[str] = None,
    mixnet_contract: Optional[str] = None,
    coin_id: Optional[str] = None,
    coingecko_base: Optional[str] = None,
    coingecko_api_key: Optional[str] = None,
    cache_dir: Optional[str] = ".cache",
    search_mode: str = "sender",
    explorer_base: Optional[str] = None,
    tx_api_base: Optional[str] = None,
    tx_rpc_base: Optional[str] = None,
    log_file: str = "nym_tax_rewards_export.log",
    log_level: str = "INFO",
) -> int:
    logger = setup_logging("nym_tax_export", log_file=log_file, level=log_level)

    if cache_dir:
        logger.debug("cache_dir is currently unused in this rewrite (fresh API calls). cache_dir=%s", cache_dir)

    wallets = load_wallets(wallets_csv)
    if not wallets:
        logger.error("No wallets found in %s", wallets_csv)
        return 2

    start_dt, end_dt = parse_date_filters(start, end)

    nyx_base = (nyx_api_base or DEFAULT_NYX_API_BASE).rstrip("/")
    nyx_tx_rest = f"{nyx_base}/cosmos/tx/v1beta1/txs"

    mixnet_addr = mixnet_contract or DEFAULT_MIXNET_CONTRACT
    explorer = explorer_base or DEFAULT_NYX_TX_REST
    tx_api = tx_api_base or nyx_tx_rest
    tx_rpc = tx_rpc_base or DEFAULT_TX_RPC_BASE
    cg_base = coingecko_base or DEFAULT_COINGECKO_BASE
    cg_coin = coin_id or "nym"

    session = build_session("nym-node-reward-tracker/reward-transactions")

    rows: List[Dict[str, Any]] = []

    with tqdm(total=len(wallets), desc="Wallets", unit="wallet") as wbar:
        for w in wallets:
            q = build_tx_query(w.address, search_mode)
            logger.info("Scanning wallet=%s tag=%s query=%r", w.address, w.tag, q)

            for tx, resp in iter_txs_by_query(
                session,
                nyx_tx_rest=nyx_tx_rest,
                query=q,
                page_limit=100,
                order_by="ORDER_BY_ASC",
                logger=logger,
                progress_desc=f"Txs {w.address[:8]}",
            ):
                ts_raw = str(resp.get("timestamp") or "")
                if not ts_raw:
                    continue
                ts_dt = parse_rfc3339_to_utc(ts_raw)

                if start_dt and ts_dt < start_dt:
                    continue
                if end_dt and ts_dt >= end_dt:
                    continue

                rows.extend(
                    build_reward_rows_for_tx(
                        wallet=w,
                        tx=tx,
                        tx_resp=resp,
                        mixnet_contract=mixnet_addr,
                        explorer_base=explorer,
                        tx_api_base=tx_api,
                        tx_rpc_base=tx_rpc,
                        logger=logger,
                        session=session,
                    )
                )

            wbar.update(1)

    if not rows:
        logger.warning("No reward-related receipts found in the selected range.")
        logger.warning("Tip: If you expected incoming transfers, try --search-mode recipient")
        return 0

    logger.info("Collected %d reward rows; fetching prices (%s)", len(rows), currency)

    enrich_rows_with_prices(
        rows,
        session=session,
        currency=currency,
        coingecko_base=cg_base,
        coin_id=cg_coin,
        api_key=coingecko_api_key,
        logger=logger,
    )

    log_rows_table(rows, currency=currency, logger=logger)
    write_rows(rows, currency=currency, out_path=out_csv)

    logger.info("Wrote %d rows to: %s", len(rows), out_csv)
    return 0

